### ISSUE TITLE
[Feature Request] Allow selection of Config Profile

### ISSUE THREAD

**Issue by fluffylea** [linuxserver/docker-ipfs#8]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I think it would be rather useful to allow configuring the IPFS server while starting the container. Now the container starts with the default configuration, which might be undesirable if the container runs connected to the Internet. The IPFS command supports [profiles](https://docs.ipfs.io/how-to/configure-node/#profiles) for this purpose.

------------------------------

## Desired Behavior
Pass the desired Configuration Profile through an environment variable to the Container, so it generates the correct configuration file automatically.

## Current Behavior
There is currently no way I know of to specify the Configuration Profile from Docker.

## Alternatives Considered
Using the `ipfs config profile apply` command you can also change the configuration profile, but it requires you manually executing a shell within the container and running the command.

**Comment by eroo36** [comment]
https://github.com/ipfs/go-ipfs/pull/5473
it was added to go-ipfs

**Comment by thelamer** [comment]
Container is no longer maintained.
